<?php
    /**
     * Recordad ordenar por orden alfabético!!
     */

    $rutas = array(
        "about_css" => "/assets/styles/css/about_css.css",
        "about_form" => "/forms/about_form.php",
        "admin_form" => "/forms/admin_form.php",
        "bootstrap_core_css" => "/assets/libs/bootstrap/css/bootstrap.min.css",
        "bootstrap_js" => "/assets/libs/bootstrap/js/bootstrap.min.js",
        "connection_bd" => "/api/connection_bd.php",
        "enigma_1_css" => "/assets/styles/css/enigma_1_css.css",
        "enigma_1_js" => "/assets/scripts/enigmas/enigma_1.js",
        "enigma_2_css" => "/assets/styles/css/enigma_2_css.css",
        "enigma_2_js" => "/assets/scripts/enigmas/enigma_2.js",
        "enigma_3_css" => "/assets/styles/css/enigma_3_css.css",
        "enigma_3_js" => "/assets/scripts/enigmas/enigma_3.js",
        "enigma_4_css" => "/assets/styles/css/enigma_4_css.css",
        "enigma_4_js" => "/assets/scripts/enigmas/enigma_4.js",
        "enigma_5_css" => "/assets/styles/css/enigma_5_css.css",
        "enigma_5_js" => "/assets/scripts/enigmas/enigma_5.js",
        "errors_bd" => "/api/errors_bd.php",
        "font_awesome_font" => "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css",
        "getUserByName" => "/api/getUserByName.php",
        "getUserById" => "/api/getUserById.php",
        "inactive_cookie" => "/assets/scripts/inactive_cookie.js",
        "index" => "/index.php",
        "index_css" => "/assets/styles/css/index_css.css",
        "jquery" => "/assets/libs/jquery/jquery-3.3.1.min.js",
        "jquery-ui" => "/assets/libs/jquery-ui/jquery-ui.min.js",
        "landing_css" => "/assets/styles/css/landing_css.css",
        "landing_form" => "/forms/landing_form.php",
        "lang_about_js" => "/assets/scripts/lang/lang_about.js",
        "lang_enigma_1_js" => "/assets/scripts/lang/lang_enigma_1.js",
        "lang_enigma_3_js" => "/assets/scripts/lang/lang_enigma_3.js",
        "lang_enigma_4_js" => "/assets/scripts/lang/lang_enigma_4.js",
        "lang_enigma_5_js" => "/assets/scripts/lang/lang_enigma_5.js",
        "lang_index_js" => "/assets/scripts/lang/lang_index.js",
        "lang_landing_js" => "/assets/scripts/lang/lang_landing.js",
        "lang_login_js" => "/assets/scripts/lang/lang_login.js",
        "lang_register_js" => "/assets/scripts/lang/lang_register.js",
        "lang_profile_js" => "/assets/scripts/lang/lang_profile.js",
        "lang_team_js" => "/assets/scripts/lang/lang_team.js",
        "locked_img" => "/assets/media/img/logo.png",
        "login_api" => "/api/login_api.php",
        "login_form" => "/forms/login_form.php",
        "login_register_css" => "/assets/styles/css/login_register_css.css",
        "logo" => "/assets/media/img/logo.png",
        "logo_ico" => "/assets/media/img/logo.ico",
        "logout_api" => "/api/logout_api.php",
        "master" => "assets/templates/master.php",
        "master_css" => "/assets/styles/css/master_css.css",
        "material_icons_font" => "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons",
        "navbar_js" => "/assets/scripts/navbar_js.js",
        "popper" => "/assets/libs/popper/popper.min.js",
        "profile_form" => "/forms/profile_form.php",
        "profile_css" => "/assets/styles/css/profile_css.css",
        "profile_js" => "/assets/scripts/profile_js.js",
        "register_api" => "/api/insertUser.php",
        "register_form" => "/forms/register_form.php",
        "register_js" => "/assets/scripts/register_js.js",
        "set_estacion_api" => "/api/logout_api.php",
        "spaceman_img" => "/assets/media/img/spaceman.png",
        "spaceship_img" => "/assets/media/img/nave.png",
        "ti" => "/assets/libs/ti/ti.php",
        "touch_punch" => "/assets/libs/touch_punch/jquery.ui.touch-punch.min.js",
        "update_dificultad_api" => "/api/update_dificultad_api.php",
        "update_user_api" => "/api/update_user_api.php",
        "user_manager_js" => "/assets/scripts/user_manager.js",
        "video_YT" => "https://www.youtube.com/embed/NtQkz0aRDe8?autoplay=1&hl=",
    );
?>